### ISSUE TITLE
Can't find the groupId / artifactId

### ISSUE THREAD

**Issue by bensavage** [kiwigrid/antora-maven-content-extension#72]
I was trying to experiment with this (it looks awesome!) but having a few issues.  When running it tells me:

[08:15:54.750] INFO (maven-content): Add Maven Content Sources to playbook...
[08:15:54.758] WARN (maven-content): failure when trying to download available versions  for undefined:undefined (Cannot read properties of undefined (reading 'split')). Skipping.
[08:15:54.759] DEBUG (maven-content): No version given.

This was trying to run the config on the readme or my own bespoke config.

Have you come across anything similar?  I had a bit of an investigation and suspect it may be a case sensitivity issue on the config...

For info:

{
  npm: '8.19.2',
  node: '18.12.1',
  v8: '10.2.154.15-node.12',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.10',
  openssl: '3.0.7+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022b',
  unicode: '14.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}

antora-documentation-demo@ /projects/antora-documentation-demo
├── @antora/cli@3.0.1
├── @antora/site-generator-default@3.0.1
├── @djencks/antora-aggregate-collector@0.1.0-beta.1
├── @kiwigrid/antora-maven-content@1.4.2
└── http-server@14.1.1

Any help much appreciated!

**Comment by krasv** [comment]
How does your playbook look like? What artifacts are you querying?

**Comment by bensavage** [comment]
I've been investigating a bit further, everything works if I change to use nvm  v16.16.0 and antora 3.0.3.  I'm guessing the extension only works on that version (apologies if I missed it somewhere starting that!) and not on antora 3.1?

**Comment by jekkel** [comment]
Hi @bensavage , thanks for the report! As @krasv said, could you please provide us an (anonymized) playbook? Maybe Antoro 3.1 changes the way how options are passed to the extension.

**Comment by jekkel** [comment]
Closing for the moment. Please re-open as soon as we have a reproducer.
